### ISSUE TITLE
Page names with page references

### ISSUE THREAD

**Issue by nckre** [logseq/db-test#111]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When creating a page that consists of other pages inline (e.g. `[[[[Hello]][[World]]]]`) the page reference looks empty in the UI.

![CleanShot 2024-09-19 at 13 51 39](https://github.com/user-attachments/assets/a85daaa5-9276-4e4b-8e1d-a359a8b2de55)

However, can create a working page like `[[[[Foo]] [[Bar]]]]` by renaming an existing page and it will be displayed correctly inline:

![CleanShot 2024-09-19 at 13 56 00](https://github.com/user-attachments/assets/e1301d07-5e51-40fb-b8b2-1222d0767d39)

When editing the above (e.g. removing space so that `[[[[Foo]] [[Bar]]]]`) the inline page ref becomes empty. 
When clicking on the ref inline, it now displays the node references.

![CleanShot 2024-09-19 at 13 58 01](https://github.com/user-attachments/assets/485e4500-cfcd-4b0c-8749-d0ce238bb4da)

### Reproduce the Bug

1. Write `[[[[Hello]][[World]]]]` into a node

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. Pages with refs in their name have [a rich history](https://github.com/logseq/logseq/issues?q=+nested+in%3Atitle+is%3Aopen+) of being buggy as they introduce a lot of edge cases. This bugginess isn't something specific to the db version and so it's less interesting unless you're proposing the behavior change for the db version

**Comment by nckre** [comment]
@logseq-cldwalker hey, my perspective for alpha test: 

* Me: I try to break things and file bug reports
* You: Decide what and how to fix it

So no worries about ignoring any of the issues I'm raising - some are extremely niche  :)

Regarding "proposing behaviour change" for nested page refs: I do believe this could be useful. But if a feature has a "_a rich history of being buggy_" and there are more important things to build -> maybe you should forbid nested references for now, same as you did with `/`

**Comment by HumanistAtypik** [comment]
Hi.

Major issue for my use case.
https://github.com/logseq/logseq/issues/11696

Actually, there is a regression in Pre-Alpha Test version compared to 0.10.9.

**Comment by HumanistAtypik** [comment]
Still a critical issue.

**Comment by miquelrosell99** [comment]
This is now more easy to do with the "Library" feature, because you can add a new line to the Library page (this creates a new page) and use [[]] there, and it will create a page with a reference to another page in the title

**Comment by HumanistAtypik** [comment]
# Table of Contents

1. Logseq's stated vision promises transcendence of hierarchies, does the implementation deliver?
   - 1.1. Logseq explicitly promised to transcend hierarchies in its funding communications
   - 1.2. Compositional page titles with nested references embody this promised transcendence
   - 1.3. This capability aligns with documented architectural patterns

2. The database migration broke compositional titles that were consistent with Logseq's vision
   - 2.1. Compositional titles with nested references functioned in Markdown version 0.10.9
   - 2.2. SQLite should have enhanced nested reference support, instead it eliminated it
   - 2.3. Documentation challenges highlight opportunities for architectural clarification

3. Logseq's existing infrastructure already supports rhizomatic structures
   - 3.1. Logseq currently supports non-hierarchical distributed structures via tags and properties
   - 3.2. The property-as-node model could unify compositional titles within a coherent rhizomatic system
   - 3.3. Explicit documentation would benefit the entire ecosystem

---

# Development

## 1. Logseq's stated vision promises transcendence of hierarchies, does the implementation deliver?

### 1.1. Logseq explicitly promised to transcend hierarchies in its funding communications

#### 1.1.1. Logseq's $4.1M funding announcement (May 2022) explicitly stated the goal of building a "World Knowledge Graph" beyond hierarchical limitations

Logseq's Series A funding round of $4.1 million from investors including Patrick Collison (Stripe), Nat Friedman (former GitHub CEO), and Tobias Lütke (Shopify) was accompanied by public statements positioning the product as building a "world knowledge graph" that would transcend traditional hierarchical limitations. This positioning establishes technical expectations: the tool's architecture should enable non-hierarchical knowledge modeling. Compositional nested titles represent one technical implementation of this principle, enabling concepts to be named by their relationships rather than their position in a tree structure. This architectural approach aligns with the stated goal of moving beyond folder-and-file metaphors toward more flexible knowledge representation.

The May 2022 funding announcement and accompanying press coverage explicitly mentioned the "World Knowledge Graph" objective and the goal of moving beyond hierarchical organizational models. This public positioning creates a technical expectation that the software will support relational structures that cannot be reduced to simple tree hierarchies. The emphasis on networked thinking in official communications suggests the architecture should support patterns like compositional references at multiple nesting levels.

#### 1.1.2. Founder Tienson Qin described Logseq as a "computer-enabled world brain" opposing systems that mimic physical folder hierarchies

Logseq's founder has consistently positioned the product as a "computer-enabled world brain" designed to reflect associative thinking patterns rather than mimicking physical filing systems. This positioning suggests the software should support complex relational patterns including multi-level nested references within page titles. The vocabulary employed in official communications ("networked thinking," "non-linear connections") aligns with technical patterns that require support for arbitrary-depth compositional structures. This philosophical foundation provides context for understanding which technical capabilities are architecturally central versus peripheral to the product's core mission.

Public communications from Tienson Qin and press coverage of Logseq systematically employ anti-hierarchical vocabulary and reference "networked thinking" principles. This consistent positioning establishes reasonable expectations regarding the software's support for advanced relational structures. The emphasis on thinking tools rather than organizational tools suggests the architecture should privilege cognitive fidelity over administrative convenience.

#### 1.1.3. Logseq's communications employ rhizomatic vocabulary (networked thinking, non-linear connections) borrowed from Deleuze and Guattari's theoretical framework

While Logseq's documentation does not explicitly invoke Deleuze and Guattari's concept of "rhizome," the vocabulary consistently employed (networked thinking, beyond hierarchies, non-linear connections) corresponds precisely to rhizomatic organizational principles. These principles require support for transversal, multidirectional relationships between all graph elements. The capacity to express complex compositional relationships directly in page titles (such as `[[The [[modeling of [[complex conceptual relations]] in [[the [[management systems]] of [[personal knowledge]]]]]] according to [[a rhizomatic architecture]]]]`) represents a direct technical implementation of these principles. Understanding this theoretical context helps clarify why certain technical patterns emerge naturally from the product's philosophical foundations.

Community discussions and technical articles regularly associate Logseq with rhizomatic organizational models, establishing reasonable expectations that the software will support technical patterns consistent with these principles, including compositional title structures. The rhizomatic metaphor provides a useful framework for understanding how different technical features relate to the product's overall architectural vision. This theoretical grounding distinguishes Logseq from tools that simply add graph visualization to traditional hierarchical databases.

### 1.2. Compositional page titles with nested references embody this promised transcendence

#### 1.2.1. Compositional titles like `[[The [[modeling]] of [[relations]]]]` express conceptual relationships hierarchies cannot capture

The technical distinction between `Methodology/Approaches/Qualitative` (hierarchical namespace) and `[[The integration of [[qualitative approaches]] and [[quantitative approaches]]]]` (compositional reference) is architecturally significant. The namespace pattern encodes an is-a-kind-of relationship, while the compositional pattern encodes compositional or interaction relationships. For knowledge graphs modeling complex conceptual domains, this distinction determines whether the architecture forces rigid classification or permits faithful modeling of actual conceptual relationships. The compositional approach enables expressing relationships like "integration of," "application to," "tension between," which cannot be naturally encoded in hierarchical paths without semantic loss or artificial page multiplication.

Version 0.10.9 based on Markdown supported this capability operationally. Documentation in GitHub issues and Discord discussions shows this pattern was actively used for academic and research knowledge graphs before the database migration. The practical utility of this pattern is demonstrated by its organic adoption for modeling complex conceptual relationships in domains ranging from philosophy to systems engineering. Users who discovered this pattern found it enabled expressing semantic relationships that were awkward or impossible to encode using hierarchical namespaces alone.

#### 1.2.2. The example `[[The [[modeling of [[complex conceptual relations]] in [[the [[management systems]] of [[personal knowledge]]]]]] according to [[a rhizomatic architecture]]]]` demonstrates multi-level nesting impossible in tree structures

A title such as `[[The [[modeling of [[complex conceptual relations]] in [[the [[management systems]] of [[personal knowledge]]]]]] according to [[a rhizomatic architecture]]]]` is not stylistic flourish but a semantic structure simultaneously expressing six distinct concepts and their relationships at multiple nesting levels. This expressiveness cannot be reproduced in traditional hierarchical systems without information loss or artificial multiplication of intermediate pages. This type of modeling represents a technical implementation of the "beyond hierarchical limitations" positioning. The ability to nest references at arbitrary depth enables capturing conceptual dependencies and relationships that mirror the actual structure of complex ideas rather than forcing them into predetermined categorical boxes.

GitHub issues #11696 and #111, along with discussion #7974, document actual usage of this syntax for academic use cases, research workflows, and complex knowledge management scenarios. These reports demonstrate operational usage for legitimate knowledge modeling patterns. The diversity of use cases—from academic literature review to software architecture documentation to philosophical concept mapping—demonstrates the generality and utility of compositional title patterns for knowledge work. The pattern emerges repeatedly in contexts where concepts naturally exhibit compositional structure or where relationships between concepts are as important as the concepts themselves.

#### 1.2.3. A tool claiming rhizomatic principles must support arbitrary recursive nesting depth in page titles

Cognitive models of human conceptual organization involve associations, connections, and multi-level conceptual nestings. Software aligned with human cognitive patterns and claiming inspiration from rhizomatic principles requires support for arbitrary recursion depth, enabling faithful capture of conceptual complexity without artificial constraints. Restricting nesting depth or eliminating this capability creates a tension with the stated "beyond hierarchical limitations" positioning. Complex ideas often involve multiple layers of qualification, context, and relationship that cannot be flattened without semantic distortion. Supporting arbitrary nesting depth is not about enabling complexity for its own sake but about providing the architectural flexibility to faithfully model ideas as they actually exist in human thought.

Natural rhizomatic structures studied in biology (mycelial networks), neuroscience (neural networks), and sociology (social networks) exhibit multiple nestings at variable depths. Empirical evidence from these domains establishes that complex adaptive systems require arbitrary relational depth. Knowledge management software refusing this depth cannot claim faithful modeling of intellectual complexity. The convergent evolution of similar patterns across biological, neural, and social systems suggests that multi-level nesting is a fundamental property of complex information systems. Software for managing complex knowledge should reflect this empirical reality rather than impose artificial simplifications.

### 1.3. This capability aligns with documented architectural patterns

#### 1.3.1. Logseq's public promise to go "beyond hierarchical limitations" establishes reasonable expectations for compositional title support

Software that positions itself as transcending hierarchical limitations creates reasonable technical expectations: implemented features should materialize this positioning. The pattern of compositional titles with deep nesting represents a direct technical expression of non-hierarchical organization. This expectation is technically grounded rather than arbitrary feature request. When a tool's marketing and philosophical positioning emphasize certain capabilities, it's reasonable for knowledge workers to expect the architecture to support patterns consistent with that positioning. The gap between stated philosophy and implemented features creates uncertainty about which technical patterns are aligned with the product's direction versus peripheral or discouraged.

Community forums, Reddit discussions, and Discord exchanges document that knowledge workers adopted Logseq specifically for its non-hierarchical positioning, having encountered limitations in tools like Notion or Obsidian. These adoption patterns demonstrate that the positioning creates specific technical expectations. The decision to adopt a tool for knowledge work represents significant investment—in learning the tool, in structuring data according to its patterns, and in building workflows around its capabilities. When adoption decisions are based on stated philosophical principles, subsequent architectural changes that contradict those principles create disruption and uncertainty.

#### 1.3.2. Investors (Collison, Friedman, Lütke) funded a deep graph architecture, not a simple two-level namespace system

Investors with technical backgrounds (Collison, Friedman, Lütke) evaluated Logseq's potential for technological differentiation in knowledge management. Their investment signals expectation of technical capabilities that meaningfully differentiate from existing hierarchical tools. Features enabling deep relational structures align with the technical differentiation these investors would have evaluated. Venture investment at this level reflects assessment that the technology offers meaningful architectural advantages over existing solutions. Understanding what attracted sophisticated technical investors provides insight into which capabilities are central to the product's competitive position versus which are implementation details.

Press releases and articles covering the funding round explicitly mention these investors and their interest in knowledge management innovation. These technologically sophisticated investors would have evaluated concrete technical differentiators rather than merely philosophical positioning. The involvement of investors who themselves have built significant technical platforms suggests they saw architectural potential beyond incremental improvements to existing tools. This context helps establish which technical capabilities are foundational to the product's value proposition versus which are optional enhancements.

#### 1.3.3. Community adoption documents show knowledge workers migrated to Logseq specifically for its promised non-hierarchical relational capabilities

Logseq's adoption by knowledge workers (academics, researchers, advanced personal knowledge management practitioners) occurred organically without aggressive marketing. This adoption pattern suggests attraction to specific technical capabilities consistent with the product's positioning. Community discussions document migration from other tools specifically citing superior relational capabilities. The organic adoption pattern—where users discover the tool through word-of-mouth recommendations from other knowledge workers—indicates the tool satisfies needs that existing alternatives don't address adequately. Understanding what drives adoption helps clarify which capabilities are differentiating versus which are table stakes.

Adoption statistics showing steady growth despite minimal marketing suggest organic adoption driven by technical capabilities aligned with the product's positioning. Community discussions consistently document migration motivated specifically by relational modeling capabilities. The willingness of knowledge workers to migrate existing knowledge bases—a high-friction activity—demonstrates strong attraction to capabilities perceived as unavailable elsewhere. This adoption pattern validates that the product's positioning resonates with real needs in the knowledge work community.

---

## 2. The database migration broke compositional titles that were consistent with Logseq's vision

### 2.1. Compositional titles with nested references functioned in Markdown version 0.10.9

#### 2.1.1. Knowledge workers successfully created and used deeply nested compositional titles in Logseq Markdown v0.10.9 for years

A software capability that functions stably over an extended period establishes a technical precedent and usage pattern. Knowledge graphs built on this functionality represent significant invested effort. Changes affecting this capability benefit from clear communication regarding future direction and migration paths. The long-term stability of this pattern enabled knowledge workers to build substantial bodies of work relying on it. Understanding that capabilities established over years create dependencies helps inform decisions about architectural evolution. The challenge of technological evolution is balancing improvement with continuity for existing users.

Version 0.10.9 based on Markdown supported compositional titles with multiple nesting levels. Screenshots, graph examples, and documentation in GitHub issues #11696 and #111 demonstrate operational functionality. This evidence shows the capability was not theoretical but operationally used. The documentation in GitHub issues provides concrete examples of how this pattern was employed for various knowledge work scenarios. These examples help illustrate the practical utility of the pattern beyond abstract technical discussion.

#### 2.1.2. Logseq's Markdown parser in v0.10.9 recursively interpreted nested `[[...]]` brackets at arbitrary depth

The Markdown parser's correct recursive interpretation of nested double brackets demonstrates the architecture possessed technical capability for handling deep compositional structures. This was not accidental behavior but logical consequence of proper parser design. Understanding how this capability emerged helps inform decisions about its future. The parser's recursive handling of bracket pairs represents a straightforward implementation that naturally enabled deep nesting. This technical simplicity suggests the capability emerged organically from the parser design rather than requiring special-case handling.

Analysis of version 0.10.9 behavior shows the Markdown parser created the main page with complete title while recognizing each nested internal link as a valid bidirectional reference. Backlinks functioned correctly at all nesting levels, demonstrating correct graph construction and maintenance. The bidirectional linking functionality—a core feature of Logseq—worked seamlessly with compositional titles, suggesting good integration with the underlying graph model. This technical integration explains why the pattern was adopted by knowledge workers: it extended existing capabilities in natural ways.

#### 2.1.3. Knowledge workers built multi-hundred page knowledge graphs in v0.10.9 structured around compositional titles

Knowledge workers who invested significant time building sophisticated knowledge systems based on compositional titles did so relying on stable software behavior. These graphs represent substantial intellectual capital. Understanding the impact of architectural changes on existing knowledge graphs helps inform migration strategies and communication approaches. The investment in structuring knowledge according to particular patterns creates switching costs when those patterns change. Balancing architectural evolution with continuity for existing users requires understanding the extent of dependency on particular patterns.

GitHub issues document knowledge graphs containing several hundred pages with compositional titles, representing years of academic or research work. The scale of affected knowledge graphs—measured in hundreds of pages representing years of work—demonstrates significant practical impact. Understanding this impact helps prioritize decisions about backward compatibility, migration tooling, and communication strategies. The time investment represented by these knowledge graphs makes migration decisions consequential.

### 2.2. SQLite should have enhanced nested reference support, instead it eliminated it

#### 2.2.1. SQLite natively supports recursive queries and arbitrary-depth relationships better than file systems

SQLite is optimized for complex many-to-many relationships, recursive structures, and queries traversing multiple nesting levels. Migration to this technology represents an opportunity to strengthen, stabilize, and extend existing relational capabilities, potentially including compositional title support. Understanding SQLite's capabilities helps identify architectural opportunities for supporting complex relational patterns. The database migration provides an opportunity to revisit which relational patterns to support and how to support them at the architectural level.

Relational databases like SQLite natively support recursive queries (WITH RECURSIVE), multiple joins, and self-referential structures. These capabilities are documented and widely used in applications managing complex graphs. SQLite's technical capabilities provide a strong foundation for supporting complex relational patterns. Understanding these capabilities helps evaluate architectural options for supporting compositional structures. The question becomes not whether the technology can support these patterns but how to design the schema and application logic to leverage the database's capabilities effectively.

#### 2.2.2. GitHub issues #11696 and #111 document that compositional titles display as empty pages or raw UUIDs in Logseq DB

A technology migration that affects existing functionality benefits from clear communication regarding the change and its rationale. Understanding the architectural considerations that informed the change helps the community evaluate alternatives and contribute constructively to solutions. The challenge of technology migrations is maintaining continuity while enabling architectural improvements. Clear communication about what changed and why helps knowledge workers understand the context for their migration decisions.

GitHub issues #11696 (open multiple years) and #111 (db-test) document the change precisely: compositional titles displaying correctly in 0.10.9 appear differently in Logseq DB—sometimes empty, sometimes showing UUIDs. Screenshots and examples provided document the functional change during migration. The visual documentation in these issues helps illustrate the specific rendering behaviors in different versions. This documentation provides a factual basis for discussing the change and evaluating potential solutions.

#### 2.2.3. Affected pages become less accessible or display technical identifiers instead of titles, affecting graph navigation

When pages display differently or show technical identifiers instead of human-readable titles, navigation patterns change for affected knowledge graphs. This affects usability for knowledge workers who structured their graphs using compositional title patterns. Understanding the navigational impact helps evaluate the urgency and priority of addressing the change. The practical impact on daily knowledge work—difficulty finding and accessing pages, disrupted navigation patterns—creates friction for affected knowledge workers.

Documentation in GitHub issues describes concrete impact: changes to page visibility, changes to how links appear in backlinks, display of UUIDs in references, modifications to the navigation experience. These symptoms are consistent for knowledge graphs employing compositional title patterns. The specificity of these descriptions helps clarify exactly what changed and how it affects typical workflows. Understanding the specific impacts helps evaluate potential solutions and their effectiveness at restoring desired functionality.

### 2.3. Documentation challenges highlight opportunities for architectural clarification

#### 2.3.1. Community discussions note the absence of official documentation explicitly addressing compositional title support in DB version

Discussion in community forums and GitHub issues observes that official documentation doesn't explicitly address the support status of compositional title patterns in the database version. This documentation gap creates uncertainty about whether this pattern is intended to work, is being worked on, or is considered outside the supported feature set. Clear documentation helps knowledge workers understand which patterns are supported and recommended versus which are experimental or deprecated. The absence of documentation creates ambiguity about the architectural direction.

Community members seeking to understand the status of this capability have noted the challenge of finding official documentation explicitly addressing compositional title support. This documentation challenge affects planning and migration decisions for knowledge workers using or considering this pattern. When documentation doesn't explicitly address a pattern that previously worked, it's unclear whether the change is temporary (a bug to be fixed), permanent (an architectural decision), or undecided (requiring further evaluation). This ambiguity makes planning difficult.

#### 2.3.2. Software capabilities that function stably over time establish usage patterns, and clear documentation helps manage transitions

In software development, capabilities that function stably over extended periods tend to be adopted into workflows even when not explicitly documented. The principle of backward compatibility in software development recognizes that stable behaviors create dependencies. Clear communication about architectural changes and their rationale helps knowledge workers understand context and make informed decisions. The challenge is balancing architectural evolution with continuity for existing users.

Industry practices around software versioning and deprecation emphasize the value of clear communication when changing established behaviors. Transparent communication about architectural decisions—particularly those affecting existing functionality—helps communities understand context and participate constructively in solutions. Even when changes are necessary for valid architectural reasons, clear explanation of the rationale and migration paths reduces friction. The goal is not to prevent all breaking changes but to manage them thoughtfully.

#### 2.3.3. Logseq's rhizomatic positioning suggests architectural patterns like compositional titles align with the product's direction

Logseq's consistent emphasis on networked thinking and non-hierarchical organization suggests that compositional relational patterns align with the product's philosophical direction. Understanding how specific technical patterns relate to broader architectural vision helps clarify which capabilities are central versus peripheral. The question becomes not whether rhizomatic principles are important but how to implement them effectively at the database level. This architectural challenge invites exploration of solutions that honor both the philosophical vision and the technical realities of database design.

Rhizomatic structures studied across multiple domains (biology, neuroscience, sociology) consistently exhibit multi-level nesting patterns. This empirical observation across diverse systems suggests that supporting arbitrary nesting depth aligns with fundamental properties of complex information systems. Software for managing complex knowledge benefits from reflecting these empirical patterns. The architectural question becomes how to support these patterns effectively while maintaining performance and usability.

---

## 3. Logseq's existing infrastructure already supports rhizomatic structures

### 3.1. Logseq currently supports non-hierarchical distributed structures via tags and properties

#### 3.1.1. Logseq's `#tag` system creates many-to-many relationships without imposing hierarchies

Logseq's tag system demonstrates the architecture already supports transversal, non-hierarchical, multiple relationships. Pages can simultaneously carry multiple tags without conflict, creating connection networks that escape tree-based logic. This existing capability demonstrates the underlying architecture is not fundamentally limited to hierarchies but supports authentically rhizomatic distributed connections. The tag system provides existence proof that the architecture can handle non-hierarchical relational patterns effectively. Understanding how tags achieve this provides insight into architectural patterns that could extend to compositional titles.

The `#tag` system functions robustly and is widely used. Advanced queries can interrogate pages by tags, creating transversal graph views. This functionality technically demonstrates Logseq efficiently manages non-hierarchical many-to-many relationships. The query capabilities built around tags show how the architecture can expose non-hierarchical relationships for analysis and navigation. This existing infrastructure could potentially extend to support compositional title patterns with similar query capabilities.

#### 3.1.2. Logseq treats properties as graph nodes with identifiers, implying their values `property:: [[value]]` are also nodes

Logseq treats properties as first-class entities (graph nodes with identifiers and metadata). Architectural consistency suggests their values should also be nodes—pages linked via `[[...]]` rather than inert strings. This logic extends naturally to page titles: if `type:: [[Natural language page]]` creates a relational edge toward a node, then a compositional title like `[[The [[modeling]] according to [[architecture]]]]` could similarly create edges toward its constituent nodes. The current architecture's treatment of properties-as-nodes provides a model for how compositional titles could be handled: each nested reference creates a node relationship.

Examination of Logseq's behavior shows properties receive internal identifiers and can be queried, linked, and enriched independently. Advanced queries can filter on `property:: [[value]]`, demonstrating the system treats property values as references to other graph nodes. This architectural pattern—treating structured data as node relationships rather than strings—could extend to compositional titles. The technical infrastructure for handling values-as-nodes already exists; the question is whether to apply it to title structures.

#### 3.1.3. Logseq's advanced query engine can traverse multiple relationship types simultaneously, proving deep graph capability

Logseq's advanced query engine sophistication, capable of simultaneously interrogating tags, page links, properties, and their values, demonstrates the architecture is already that of a true deep knowledge graph. Queries can traverse multiple relationship levels and extract information according to complex crossed criteria. This existing technical capability suggests compositional title support with deep nestings is architecturally feasible. The query engine's capabilities demonstrate the database and application layers can handle complex relational traversals efficiently.

Advanced knowledge workers regularly create queries traversing multiple link types: `{:query [:find ?page :where [?page :block/properties ?props] [(get ?props :type) ?type] [(= ?type "Natural language page")]]}`. These queries function reliably and demonstrate the engine can navigate complex relational structures. This validates technical feasibility of extending similar capabilities to compositional titles. The query language's expressiveness provides a foundation for sophisticated interaction with any relational pattern the system supports.

### 3.2. The property-as-node model could unify compositional titles within a coherent rhizomatic system

#### 3.2.1. Pages with compositional titles could automatically receive distinguishing properties for identification and special handling

A technically elegant approach would leverage the existing property-as-node model. Pages whose titles contain nested double brackets could automatically receive distinctive properties enabling identification and appropriate handling. For example: `type:: [[Natural language page]]` (simple form) or `type:: [[[[Page·s]] in [[[[language]] [[natural]]]]]]` (maximally compositional form). This marking would enable special treatment where needed while preserving coexistence of different usage patterns. The automatic property assignment would make compositional pages queryable and identifiable without requiring manual tagging.

This approach relies on existing documented Logseq mechanisms. Automatic properties (like `created-at::` or `updated-at::`) demonstrate the system can automatically assign metadata to pages. Extending this mechanism to compositional titles would leverage proven patterns rather than requiring entirely new architectural approaches. The property system's flexibility enables marking pages for special handling while maintaining backward compatibility with existing graphs. Pages not using compositional titles would remain unchanged.

#### 3.2.2. Simple-title pages could retain their own distinguishing properties, enabling peaceful coexistence of organizational paradigms

This approach would not invalidate existing usages or force a single organizational model. Pages using hierarchical namespaces or simple titles could retain their own distinctive properties indicating their organizational pattern. This technical coexistence would allow knowledge workers who prefer hierarchical organization to continue without disruption while providing alternatives for those needing compositional structures. The goal is supporting multiple valid organizational paradigms within a single system.

Mature knowledge management systems (like Emacs Org-mode or TiddlyWiki) have supported coexistence of multiple structuring paradigms without conflict for years. This empirical existence proof demonstrates the approach is technically viable and proven in real large-scale contexts. The key insight is that different organizational paradigms serve different needs; supporting multiple paradigms increases the system's flexibility and applicability. Rather than forcing all knowledge into a single organizational model, the system can adapt to different organizational needs.

#### 3.2.3. All page types would coexist as equal graph nodes, fulfilling Logseq's "World Knowledge Graph" vision of accommodating diverse organizational approaches

The result would be a truly rhizomatic system where multiple structuring modes coexist harmoniously without any imposed as superior or exclusive. Simple titles, namespace hierarchies, and compositional titles would all be first-class graph citizens with equal rights and adapted treatments. This inclusive coexistence would materialize the "world knowledge graph" vision capable of accommodating diversity of thought modes and cognitive preferences. Different knowledge workers organize information differently; supporting this diversity makes the tool more universally applicable.

The fact that all property values are treated as nodes guarantees these annotations actively participate in the relational network, able to be queried, enriched, and linked. This architecture is already implemented and functional. Extending it to compositional titles would be consistent with existing architectural patterns rather than introducing fundamentally new approaches. The question is not whether the architecture can support this but whether to design the feature to leverage existing infrastructure.

### 3.3. Explicit documentation would benefit the entire ecosystem

#### 3.3.1. GitHub issues #11696 and #111 remain open without official resolution after multiple years, creating planning uncertainty

Absence of clear official communication for several years creates operational uncertainty for affected knowledge workers. Unclear status prevents informed planning decisions: whether to wait for resolution, restructure existing graphs, or consider alternative tools. This planning uncertainty affects both individual knowledge workers and the broader community. Clear communication—even if the news is that certain patterns won't be supported—enables informed decision-making. The uncertainty is more problematic than definitive information, even when that information involves difficult tradeoffs.

GitHub issues #11696 and #111 have remained open for years, documenting the issue and community discussion but without official team resolution or response. Discord discussions show ongoing questions about this capability's status and future. This documented absence of official communication compounds the technical change's impact. The community's self-organization around documenting the issue and exploring workarounds demonstrates engagement and desire for resolution. Official engagement with these discussions would help channel this community energy productively.

#### 3.3.2. Clear architectural communication benefits planning for knowledge workers, extension developers, and the Logseq team

Clear communication about architectural decisions and their rationale—even when those decisions involve tradeoffs—benefits all ecosystem participants. Knowledge workers can make informed planning decisions. Extension developers understand which patterns will have long-term support. The Logseq team benefits from community understanding of architectural constraints and opportunities. Transparency reduces friction and enables constructive collaboration around solutions.

Open-source project management practices emphasize transparent communication about major architectural decisions. This includes not just what changed but why—the considerations, tradeoffs, and constraints that informed the decision. Even when decisions involve difficult tradeoffs that don't satisfy all use cases, explaining the reasoning helps the community understand context and participate constructively in refinements. The goal is collaborative problem-solving rather than unilateral decision-making.

#### 3.3.3. Successful open-source projects (Linux, Firefox, VS Code) demonstrate transparent architectural communication as ecosystem health practice

Mature open-source projects maintain transparent communication about architectural decisions through RFCs, labeled issues, and public roadmaps. This is not optional administrative overhead but essential practice for ecosystem health. Logseq, as a well-funded project ($4.1M) targeting a broad community, would benefit from adopting these communication practices. Transparent architectural communication builds trust, enables informed decision-making, and facilitates community contribution. The investment in clear communication pays dividends in reduced friction and increased collaboration.

Examples from successful projects show various approaches to architectural communication: Linux uses mailing lists and documentation for kernel development decisions, Firefox publishes detailed architecture plans and RFCs, VS Code maintains public roadmaps and issue triage. The specific mechanisms vary, but the principle is consistent: major architectural decisions benefit from clear explanation of rationale, tradeoffs, and direction. This enables the community to understand context, adapt to changes, and contribute constructively to solutions. The result is stronger ecosystem alignment and reduced friction around inevitable changes.

---

## Conclusion and Path Forward

This document has explored three interconnected questions: Does Logseq's implementation align with its stated vision? What happened to compositional title support during the database migration? How might the existing infrastructure support this capability?

The analysis suggests compositional titles align with Logseq's rhizomatic positioning, functioned operationally in v0.10.9, and could potentially be supported using existing architectural patterns like property-as-node. The core challenge is not primarily technical feasibility but architectural decision-making about which patterns to support and how.

Clear communication about the architectural direction would benefit all ecosystem participants. Whether the decision is to restore full support, provide graceful degradation, or recommend alternative patterns, explicit documentation would enable informed planning and reduce current uncertainty.

The Logseq community has demonstrated remarkable creativity in adapting the tool to diverse knowledge work needs. This document is offered in that collaborative spirit: as analysis of architectural questions, documentation of empirical usage patterns, and exploration of potential technical approaches. The goal is contributing constructively to the ongoing evolution of this valuable tool.

**Comment by HumanistAtypik** [comment]
> This is now more easy to do with the "Library" feature, because you can add a new line to the Library page (this creates a new page) and use [[]] there, and it will create a page with a reference to another page in the title

Even when every needed page is created, the problem remains...

**Comment by tiensonqin** [comment]
Fixed in the latest version.

**Comment by HumanistAtypik** [comment]
According to GLM-2, tested on nightly 20260908 — the problem persists. Here is a minimal reproduction with a local code investigation.

## Minimal reproduction (escaladed by removing one semantic layer at a time)

| # | Editing mode (focused) | Display mode (unfocused) |
|---|---|---|
| 1 | `[[[[Mon]] [[[[[[Système]] [[[[sémiotico]]-[[informatique]]]]]] [[personnel]]]]]]` | `[[[[[[6aa24cba-b4c5-4e3e-8177-f711f140f8a8]] [[[[[[...]] [[...]]]] [[...]]]]]]]]` |
| 2 | `[[Mon]] [[[[[[Système]] [[[[sémiotico]]-[[informatique]]]]]] [[personnel]]]]` | `[[[[Mon]] [[[[[[[[...]] [[...]]]] [[...]]]]]]` |
| 3 | `[[Mon]] [[[[Système]] [[[[sémiotico]]-[[informatique]]]]]] [[personnel]]` | `[[Mon]] [[[[[[...]] [[...]]]]]] [[personnel]]` |
| 4 | `[[Mon]] [[Système]] [[[[sémiotico]]-[[informatique]]]] [[personnel]]` | `[[Mon]] [[Système]] [[[[sémiotico]]-[[informatique]]]] [[personnel]]` |

- `...` = UUID matricules (e.g. `6aa24cba-b4c5-4e3e-8177-f711f140f8a8`), not page names.
- The hyphen `-` between `[[sémiotico]]` and `[[informatique]]` is absent in rows 1–3, present in row 4.
- Row 4 display = editing mode (correct).

## Root cause: `sort-refs` in `title-ref->id-ref`

`sort-refs` (`deps/db/src/logseq/db/frontend/content.cljs:30-39`) sorts refs by `[has-nested-brackets, title]` descending. The sort key is:

```clojure
[(boolean (re-find page-ref/page-ref-without-nested-re title)) title]
```

For a composite page like "système sémiotico-informatique" (title `[[Système]] [[[[sémiotico]]-[[informatique]]]]`), `sort-refs` puts the inner page "sémiotico-informatique" (title `[[sémiotico]]-[[informatique]]`) **before** the composite, because `s` (115) > `S` (83) in ASCII.

`title-ref->id-ref` then replaces `[[[[sémiotico]]-[[informatique]]]]` → `[[uuid-sémio-info]]` first. This mutates the content inside the composite's pattern. When `title-ref->id-ref` tries to replace the composite (`[[[[Système]] [[[[sémiotico]]-[[informatique]]]]]] [[personnel]]]]`), the pattern no longer matches. **The composite UUID is never stored.**

I confirmed this by querying the SQLite DB directly. The raw-title of the block on page "système sémiotico-informatique personnel" contains:
```
[[[[[[uuid-Système]] [[uuid-sémiotico-informatique]]]] [[uuid-personnel]]]]
```
instead of `[[uuid-composite]]`. The intermediate composite UUIDs are never stored — only the leaf UUIDs.

## mldoc parses correctly — the failure is in Logseq's rendering

I ran mldoc 1.5.9 locally on the actual raw-titles. mldoc produces valid ASTs:
- `[[uuid]]` alone (1 child) → falls back to `Page_ref` → `Link {url: Page_ref "uuid"}`
- `[[uuid-A]] [[uuid-B]]` (>1 child) → `Nested_link` with structured children

mldoc's `match_brackets` does proper bracket matching by counting `[[`/`]]` levels. It correctly parses arbitrarily nested UUIDs. The parser is not the problem.

## Rendering: `nested-link` → `db/get-page` → fallback → bracket accumulation

When Logseq renders a `Nested_link` from the AST:

1. `nested-link` (`block.cljs:1421-1437`) extracts `page-name = subs(content, 2, len-2)` — the content without outermost brackets. For a composite, this is a string like `[[uuid-A]] [[uuid-B]]`.
2. `page-cp` → `page-cp-inner` → `db/get-page` on this composite string. `parse-uuid` fails (not a pure UUID). `get-first-page-by-name` fails (not a page name). The page is not found.
3. Async load via `<get-block` also fails (same reason).
4. `show-non-exists-page?` is `nil` in the normal rendering chain (only set by `property/value.cljs` and `all_pages.cljs`).
5. Fallback case 3 (`block.cljs:1017-1021`): displays `[[ + :block/name + ]]`. Children are **ignored**.
6. `nested-link` adds its own `[[ ]]` (`block.cljs:1426-1437`).

Result: **+2 bracket pairs per unresolved level**, and the children from the mldoc AST are lost.

For `Page_ref` (isolated UUIDs), `page-reference` → `db/get-page` → `parse-uuid` succeeds → page found → `page-inner` (`block.cljs:792-819`) displays the resolved title as **plain text** (no re-parsing by mldoc). Internal `[[ ]]` in the resolved title are rendered as characters, not as clickable links.

## The hyphen `-`

The hyphen is in the page title (`[[sémiotico]]-[[informatique]]`), not in the block's raw-title. When rendering fails (UUIDs displayed as raw text via fallback), the hyphen is absent. When rendering succeeds (row 4, `Page_ref` resolved → `page-inner` displays the resolved title), the hyphen is present.

## `recur-replace-uuid-in-block-title` is not on the rendering path

`recur-replace-uuid-in-block-title` (`content.cljs:171-195`, PR #12536 by @tiensonqin) does recursive UUID→title resolution (depth 10, BFS). It works — the added tests confirm it. But it is only called by:
- `frontend/common/file/core.cljs:41` (file export)
- `frontend/worker/search.cljs:230` (search index)
- `frontend/components/property/value.cljs:749` (property values)

`get-block-title` (`entity_plus.cljc:102`) calls `id-ref->title-ref` (single-pass, non-recursive) instead. The fix exists but is not on the rendering path.

## Summary

| Bug | Location | Mechanism |
|-----|----------|-----------|
| Composite UUID not stored | `content.cljs:30-39` sort-refs | `s` > `S` sorts inner before composite, breaks pattern |
| Page not found in rendering | `block.cljs:1430` nested-link → `db.cljs:260` | `parse-uuid` fails on composite string |
| Bracket pairs induced | `block.cljs:1426` + `block.cljs:1019` | nested-link + fallback each add `[[ ]]` |
| Children ignored | `block.cljs:1017-1021` | fallback case 3, no `show-non-exists-page?` |
| Title as plain text | `block.cljs:792-819` | no re-parsing of resolved title |
| Recursive fix not used | `entity_plus.cljc:102` | `id-ref->title-ref` instead of `recur-replace` |
