### ISSUE TITLE
Scrolling horrifically slow with a table in view

### ISSUE THREAD

**Issue by faldor20** [logseq/db-test#141]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

The moment a table is in view, scrolling becomes ridiculously slow. (200ms to render a frame).
I attached a performance trace, but it looks like react is doing some serious churn from the onscroll event. 
I suspect this is just the classic, react re-rendering elements when it really should't be type issue.
 
I found removing all the columns improved things.

[Trace-20241016T000741.json](https://github.com/user-attachments/files/17379735/Trace-20241016T000741.json)

### Reproduce the Bug

1. Have a slowish computer
2. Go to a page with a table with a few properties >4 is choppy, for me at about 10 it's unusable. My table had 5 entries
3. scroll with the table in view.

### Expected Behavior

Tables shouldn't cause huge slowdown when scrolling

### Browser, Desktop or Mobile Platform Information

Linux, google chrome, wayland

### Additional Context

#126 Is simillar, but my issue occurs on any page with a table regardless of size

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tiensonqin** [comment]
Closing since the bug has been addressed with the latest version.

**Comment by digitallyoli** [comment]
I think I'm still experiencing something similar to this issue. 

There's a noticeable delay before the next section of the table renders when scrolling.

https://github.com/user-attachments/assets/c8b5574c-777f-46a9-b323-9b8fa93c4b46
