### ISSUE TITLE
View filtering and group by does not work for :default properties

### ISSUE THREAD

**Issue by kerim** [logseq/db-test#264]
### Search first

- [x] I searched and no similar issues were found

### What Happened?

I created a MD graph, then imported it to the DB version. However, after import filters and "group by" options do not work as expected.

### Reproduce the Bug

Try to filter out "helper" apps, or try to group by "apptype" and it does not work properly.

### Files

[apps_logseq.md](https://github.com/user-attachments/files/19935887/apps_logseq.md)

[logseq_db_logseq app db_1745825364.edn.zip](https://github.com/user-attachments/files/19935890/logseq_db_logseq.app.db_1745825364.edn.zip)

### Browser, Desktop or Mobile Platform Information

commit/7346266
Brave browser
MacOS 

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kerim** [comment]
Here are some pictures showing the failure to group by apptype and the failure to filter out "helper" apps, even when that filter is on. 

<img width="993" alt="Image" src="https://github.com/user-attachments/assets/9556c38f-4f1a-4aa7-8fc7-d17cd048d3d5" />
<img width="276" alt="Image" src="https://github.com/user-attachments/assets/5bec8e1e-4eed-48f2-b9e8-97c6e4a39a95" />
<img width="173" alt="Image" src="https://github.com/user-attachments/assets/28aabf80-a621-421a-bf55-955bfe6fd382" />
<img width="184" alt="Image" src="https://github.com/user-attachments/assets/89ac4af4-9249-422b-a0e6-1f64fb8d3d73" />
<img width="283" alt="Image" src="https://github.com/user-attachments/assets/b1604b6b-dd40-43d3-8331-d8342f307809" />

**Comment by logseq-cldwalker** [comment]
Hi. This seems to be a larger issue with group by. I can reproduce this on a new graph by creating a :default apptype property and then creating multiple blocks with the same property and property value of "helper". We're looking at ways to fix this

**Comment by logseq-cldwalker** [comment]
I've pushed up a fix to test which should be available in ~10 min

**Comment by kerim** [comment]
So it seems there were two separate bugs here. (Sorry about that.) 

First, the "group by" bug. This does seem to be fixed. Thanks.

Second, the inability to filter by "apptype." This is still not fixed. 

I imported my own edn into a new graph, and while I can now "group by" correctly, I still cannot create a filter such as "apptype is NOT helper" and actually filter out that apptype.

**Comment by logseq-cldwalker** [comment]
Ah, I missed the filtering part. I've pushed a fix that'll be on test in ~10 min

**Comment by kerim** [comment]
All working now. Thanks!
