### ISSUE TITLE
Convert page to tag does not work when page-reference name contains paranthesis "()"

### ISSUE THREAD

**Issue by Zyrohex** [logseq/db-test#4]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

When trying to convert a page to a tag, the convert process fails if the page reference name contains parenthesis = "[[Deep Neural Networks (DNN)]]"

### Reproduce the Bug

1. Create a page reference with anything that contains an abbreviation wrapped in Parenthesis or just has an open/close parenthesis.
2. Navigate to the page reference page and right click on the page title and choose "Convert to tag"

### Expected Behavior

The page should have been converted to a tag class

### Browser, Desktop or Mobile Platform Information

Logseq DB Test Environment
Revision = https://github.com/logseq/logseq/commit/046e81b

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by Zyrohex** [comment]
https://github.com/user-attachments/assets/405781d9-9b71-4cd1-8dd1-623c62de6a40

**Comment by tiensonqin** [comment]
Thanks! I can reproduce this one.

**Comment by tiensonqin** [comment]
This bug should be fixed now, I will re-open if it doesn't work.

**Comment by Zyrohex** [comment]
Still reproducing the same bug as of 5 mins ago on commit = https://github.com/logseq/logseq/commit/86d031c

**Comment by logseq-cldwalker** [comment]
@Zyrohex While adding tests for this fix I wasn't able to reproduce it on https://test.logseq.com/ with https://github.com/logseq/logseq/pull/9858/commits/0876198cca773e55c198ac111225c6e893fc5f90. If it's still reproducible, please let us know with what text

**Comment by Zyrohex** [comment]
@logseq-cldwalker - my mistake! I re-tested this later that day and it did not reproduce. The test environment did not contain the latest commit changes when I tested earlier that day. This is resolved I just forgot to respond. :)
