### ISSUE TITLE
Can't import EDN of tag page when properties are assigned

### ISSUE THREAD

**Issue by kerim** [logseq/db-test#549]
### Search first

- [x] I searched and no similar issues were found

### What Happened?

I am trying to export a tag page from one graph and import it to another. It works if there are no properties set for the graph, but not if properties are set.

### Reproduce the Bug

Importing this has no error:

```
{:pages-and-blocks
 [{:page
   {:build/tags [:logseq.class/Tag],
    :build/properties
    {:logseq.property.class/extends #{:logseq.class/Root}},
    :block/title "noprop"},
   :blocks
   [{:block/title "Random text",
     :build/properties {},
     :build/children
     [{:block/title "more random text", :build/properties {}}]}]}],
 :logseq.db.sqlite.export/export-type :page}

```

But this produces the error documented in the console log below:

```
{:pages-and-blocks
 [{:page
   {:block/collapsed? false,
    :build/tags [:logseq.class/Tag],
    :build/properties
    {:logseq.property.class/extends #{:logseq.class/Root},
     :logseq.property.class/properties
     #{:user.property/sampleprop-OGMEwUv0}},
    :block/title "prop"},
   :blocks []}], 
 :logseq.db.sqlite.export/export-type :page}

```

### Expected Behavior

Both should import

### Files

Cosole log

```
db.cljs:135 :debug :transact-failed :tx-meta {:logseq.db.sqlite.export/imported-data? true} :tx-data ({:block/uuid #uuid "826070eb-c44f-4a77-9f50-7e1a539c39e9", :block/updated-at 1762061836617, :logseq.property.class/extends #{:logseq.class/Root}, :logseq.property.class/properties #{:user.property/sampleprop-OGMEwUv0}, :block/created-at 1762061836617, :block/collapsed? false, :block/tags [{:db/ident :logseq.class/Tag}], :block/title "prop", :db/id -4, :block/name "prop"})
utils.js:19 Unexpected webworker error: up {meta: null, obj: {…}, Wa: true, Sa: ƒ, za: ƒ, …}
console.error @ utils.js:19
(anonymous) @ instrument.js:112
QNb.a.onmessage @ worker.cljs:92
worker.cljs:93 Error: Nothing found for entity id :user.property/sampleprop-OGMEwUv0
    at new Cn (db-worker.js?electron=false&publishing=false:714:26)
    at Fn (db-worker.js?electron=false&publishing=false:716:64)
    at En (db-worker.js?electron=false&publishing=false:716:25)
    at QQ (db-worker.js?electron=false&publishing=false:1326:51)
    at hR (db-worker.js?electron=false&publishing=false:1347:442)
    at jR (db-worker.js?electron=false&publishing=false:1363:62)
    at BR (db-worker.js?electron=false&publishing=false:1383:261)
    at b_a (db-worker.js?electron=false&publishing=false:2593:137)
    at n1.j (db-worker.js?electron=false&publishing=false:2595:272)
    at U$ (db-worker.js?electron=false&publishing=false:4315:20)
utils.js:19 [frontend.handler] {:exception #error {:message "Promise error", :data {:error :promise-error}, :cause #object[Error Error: Nothing found for entity id :user.property/sampleprop-OGMEwUv0]}, :line 51}
console.error @ utils.js:19
(anonymous) @ instrument.js:112
fia @ core.cljs:3996
gia @ core.cljs:3991
$APP.Gf.A @ core.cljs:3985
(anonymous) @ console.cljs:33
c @ glogi.cljs:199
(anonymous) @ log.js:702
Bca @ log.js:701
Mca @ log.js:994
Jj @ glogi.cljs:26
DPc.window.onerror @ handler.cljs:51
sa.onerror @ instrument.js:509
utils.js:19 [frontend.handler] #error {:message "Promise error", :data {:error :promise-error}, :cause #object[Error Error: Nothing found for entity id :user.property/sampleprop-OGMEwUv0]} 
 Error: Promise error
    at new $APP.ji (https://test.logseq.com/js/main.js:5560:91)
    at $APP.Kk.C (https://test.logseq.com/js/main.js:11157:319)
    at Object.reject (https://test.logseq.com/js/main.js:7191:434)
    at uya (https://test.logseq.com/js/main.js:5878:141)
    at vya (https://test.logseq.com/js/main.js:5876:180)
    at In.reject (https://test.logseq.com/js/main.js:12743:371)
    at Object.complete (https://test.logseq.com/js/main.js:5878:285)
    at Object.complete (https://test.logseq.com/js/main.js:5877:287)
    at yya (https://test.logseq.com/js/main.js:5877:47)
    at uya (https://test.logseq.com/js/main.js:5878:197)
    at vya (https://test.logseq.com/js/main.js:5876:180)
    at In.reject (https://test.logseq.com/js/main.js:12743:371)
    at Object.complete (https://test.logseq.com/js/main.js:5878:285)
    at yya (https://test.logseq.com/js/main.js:5877:47)
    at uya (https://test.logseq.com/js/main.js:5878:197)
    at vya (https://test.logseq.com/js/main.js:5876:180)
    at In.reject (https://test.logseq.com/js/main.js:12743:371)
    at https://test.logseq.com/js/main.js:5880:114
console.error @ utils.js:19
(anonymous) @ instrument.js:112
(anonymous) @ console.cljs:35
c @ glogi.cljs:199
(anonymous) @ log.js:702
Bca @ log.js:701
Mca @ log.js:994
Jj @ glogi.cljs:26
DPc.window.onerror @ handler.cljs:51
sa.onerror @ instrument.js:509
ioc_helpers.cljs:45 Uncaught $APP.ji {message: 'Promise error', data: $…P.m, cause: Error: Nothing found for entity id :user.property/sampleprop-OGMEwUv0
    at new Cn (https://test.l…, name: 'Error', description: undefined, …}
Zi @ ioc_helpers.cljs:45
(anonymous) @ ioc_helpers.cljs:56
(anonymous) @ channels.cljs:65
mma @ dispatch.cljs:27
Kba.b.port1.onmessage @ nexttick.js:195
index.js:962 Uncaught $APP.ji {message: 'Promise error', data: $…P.m, cause: Error: Nothing found for entity id :user.property/sampleprop-OGMEwUv0
    at new Cn (https://test.l…, name: 'Error', description: undefined, …}
Se @ index.js:962
(anonymous) @ index.js:964

```

### Browser, Desktop or Mobile Platform Information

MacOS, Chrome Browser
https://github.com/logseq/logseq/commit/b847cfb

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. I've pushed a fix that should be available in ~10 min on test

**Comment by kerim** [comment]
Hmmm. My second example still doesn't import, but now it gives an error message: "Unexpected Import EDN error: "Nothing found for entity id :user.property/sampleprop-OGMEwUv0" Is this expected behavior? 

https://github.com/logseq/logseq/commit/ef68e19

**Comment by logseq-cldwalker** [comment]
The underlying issue was an invalid, buggy export. If you re-export the page, you'll get a valid export. I've also added a validation check for page exports so that an invalid export errors during export instead of later on import as you experienced

**Comment by logseq-cldwalker** [comment]
Closing as this is fixed but feel free to let me know otherwise
