### ISSUE TITLE
Multiple issues when importing a graph

### ISSUE THREAD

**Issue by kerim** [logseq/db-test#61]
### Search first

- [X] I searched and no similar issues were found

### What Happened?

As far as I can tell, all my block refs are broken on import to the DB version. I got hundreds of "No uuid found for page name nil" on import, and after import all my block refs just look like a string of numbers, and don't link to the actual block. I don't know if this is an error or if block ref import hasn't been implemented yet?

### Reproduce the Bug

Import MD graph

### Expected Behavior

Block refs should work.

### Screenshots

n/a

### Browser, Desktop or Mobile Platform Information

n/a

### Additional Context

n/a

### Are you willing to submit a PR? If you know how to fix the bug.

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by logseq-cldwalker** [comment]
Hi. I can't reproduce this error. Could you provide some example pages that are causing this error? If you'd prefer to keep the page content private, feel free to email gabriel@logseq.com

**Comment by kerim** [comment]
Sure, but it will take me some time to try to do this in a way that I can share it, without sharing my entire DB...

**Comment by logseq-cldwalker** [comment]
@kerim I've pushed a support for custom title formats on journals. Should be up on test.logseq.com in ~10m. I don't think it will resolve some other issues you are seeing but it will at least respect a critical config your graph relies on

**Comment by logseq-cldwalker** [comment]
I looked at a couple of the issues with your graph (as you know via private email). The most concerning issue was "No uuid found for page name ..." errors being displayed. Unfortunately I was unable to reproduce these issues with the given files including the graph's config.edn. I did see that your graph uses the a custom title-format for journals so I added import support for that. As I'm fixing other import issues hopefully they will start to address some issues you're seeing. Closing this since I'm unable to reproduce a specific issue

**Comment by kerim** [comment]
Thanks. Just did a new import. I still have the No uuid found for page name error, but it happened far less often this time (only 24 times). Also, the issue we worked on where the ID was displayed instead of [[page title]] is no longer there. I will see if I can identify what is going on with the pages that still have errors and file a new report if I can.

**Comment by kerim** [comment]
Also, I don't know if it had any effect or not. But I realized that I was previously using the "#journal" tag which now conflicts with the built-in journal tag in the DB version, so I renamed that to #diary before import. I just mention it in case that might have helped reduce some errors.

**Comment by logseq-cldwalker** [comment]
Glad to hear it's improved. Fixing a bug related to
https://github.com/logseq/db-test/issues/134 likely fixed most of your
issues. Good to know about renaming '#journal'
